version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"            # Access the React app at http://localhost:3000
    environment:
      - VITE_DAILY_ROOM_URL=${DAILY_ROOM_URL}
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"          # FastAPI is available at http://localhost:8000
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - DAILY_API_KEY=${DAILY_API_KEY}
      - DAILY_ROOM_URL=${DAILY_ROOM_URL}
    volumes:
      - db_data:/app/data     # Persist SQLite data
volumes:
  db_data:
