version: "3.9"
services:
  frontend:
    build: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/chat_history.db:/app/chat_history.db
