version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"              # Access the app at http://localhost:80
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - DAILY_API_KEY=${DAILY_API_KEY}
      - DAILY_ROOM_URL=${DAILY_ROOM_URL}
    volumes:
      - db_data:/app/data     # Persist SQLite data

volumes:
  db_data:    # Named volume for database persistence
